/*
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ui;

import com.google.inject.Injector;
import fr.ytpdsl.ui.internal.YtpdslActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class YtpDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(YtpdslActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		YtpdslActivator activator = YtpdslActivator.getInstance();
		return activator != null ? activator.getInjector(YtpdslActivator.FR_YTPDSL_YTPDSL) : null;
	}

}
