/*
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractYtpDslScopeProvider extends DelegatingScopeProvider {
}
