/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl.util;

import fr.ytpdsl.ytpDsl.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage
 * @generated
 */
public class YtpDslAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static YtpDslPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public YtpDslAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = YtpDslPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected YtpDslSwitch<Adapter> modelSwitch =
    new YtpDslSwitch<Adapter>()
    {
      @Override
      public Adapter caseYtpModel(YtpModel object)
      {
        return createYtpModelAdapter();
      }
      @Override
      public Adapter caseGeneratorInformation(GeneratorInformation object)
      {
        return createGeneratorInformationAdapter();
      }
      @Override
      public Adapter caseVideoLibrary(VideoLibrary object)
      {
        return createVideoLibraryAdapter();
      }
      @Override
      public Adapter caseMedia(Media object)
      {
        return createMediaAdapter();
      }
      @Override
      public Adapter caseMediaDescription(MediaDescription object)
      {
        return createMediaDescriptionAdapter();
      }
      @Override
      public Adapter caseImageDescription(ImageDescription object)
      {
        return createImageDescriptionAdapter();
      }
      @Override
      public Adapter caseVideoDescription(VideoDescription object)
      {
        return createVideoDescriptionAdapter();
      }
      @Override
      public Adapter caseVideoText(VideoText object)
      {
        return createVideoTextAdapter();
      }
      @Override
      public Adapter caseFilter(Filter object)
      {
        return createFilterAdapter();
      }
      @Override
      public Adapter caseBlackWhiteFilter(BlackWhiteFilter object)
      {
        return createBlackWhiteFilterAdapter();
      }
      @Override
      public Adapter caseNegateFilter(NegateFilter object)
      {
        return createNegateFilterAdapter();
      }
      @Override
      public Adapter caseFlipFilter(FlipFilter object)
      {
        return createFlipFilterAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.YtpModel <em>Ytp Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.YtpModel
   * @generated
   */
  public Adapter createYtpModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.GeneratorInformation <em>Generator Information</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.GeneratorInformation
   * @generated
   */
  public Adapter createGeneratorInformationAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.VideoLibrary <em>Video Library</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.VideoLibrary
   * @generated
   */
  public Adapter createVideoLibraryAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.Media <em>Media</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.Media
   * @generated
   */
  public Adapter createMediaAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.MediaDescription <em>Media Description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.MediaDescription
   * @generated
   */
  public Adapter createMediaDescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.ImageDescription <em>Image Description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.ImageDescription
   * @generated
   */
  public Adapter createImageDescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.VideoDescription <em>Video Description</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.VideoDescription
   * @generated
   */
  public Adapter createVideoDescriptionAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.VideoText <em>Video Text</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.VideoText
   * @generated
   */
  public Adapter createVideoTextAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.Filter
   * @generated
   */
  public Adapter createFilterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.BlackWhiteFilter <em>Black White Filter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.BlackWhiteFilter
   * @generated
   */
  public Adapter createBlackWhiteFilterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.NegateFilter <em>Negate Filter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.NegateFilter
   * @generated
   */
  public Adapter createNegateFilterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link fr.ytpdsl.ytpDsl.FlipFilter <em>Flip Filter</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see fr.ytpdsl.ytpDsl.FlipFilter
   * @generated
   */
  public Adapter createFlipFilterAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //YtpDslAdapterFactory
