/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getFilter()
 * @model
 * @generated
 */
public interface Filter extends EObject
{
} // Filter
