/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flip Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ytpdsl.ytpDsl.FlipFilter#getOrientation <em>Orientation</em>}</li>
 * </ul>
 *
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getFlipFilter()
 * @model
 * @generated
 */
public interface FlipFilter extends Filter
{
  /**
   * Returns the value of the '<em><b>Orientation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Orientation</em>' attribute.
   * @see #setOrientation(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getFlipFilter_Orientation()
   * @model
   * @generated
   */
  String getOrientation();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.FlipFilter#getOrientation <em>Orientation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Orientation</em>' attribute.
   * @see #getOrientation()
   * @generated
   */
  void setOrientation(String value);

} // FlipFilter
