/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Generator Information</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getAuthorName <em>Author Name</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getVersion <em>Version</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getCreationDate <em>Creation Date</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getFfmpeg <em>Ffmpeg</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getFfprobe <em>Ffprobe</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getLibrary <em>Library</em>}</li>
 * </ul>
 *
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getGeneratorInformation()
 * @model
 * @generated
 */
public interface GeneratorInformation extends EObject
{
  /**
   * Returns the value of the '<em><b>Author Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Author Name</em>' attribute.
   * @see #setAuthorName(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getGeneratorInformation_AuthorName()
   * @model
   * @generated
   */
  String getAuthorName();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getAuthorName <em>Author Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Author Name</em>' attribute.
   * @see #getAuthorName()
   * @generated
   */
  void setAuthorName(String value);

  /**
   * Returns the value of the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Version</em>' attribute.
   * @see #setVersion(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getGeneratorInformation_Version()
   * @model
   * @generated
   */
  String getVersion();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getVersion <em>Version</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Version</em>' attribute.
   * @see #getVersion()
   * @generated
   */
  void setVersion(String value);

  /**
   * Returns the value of the '<em><b>Creation Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Creation Date</em>' attribute.
   * @see #setCreationDate(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getGeneratorInformation_CreationDate()
   * @model
   * @generated
   */
  String getCreationDate();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getCreationDate <em>Creation Date</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Creation Date</em>' attribute.
   * @see #getCreationDate()
   * @generated
   */
  void setCreationDate(String value);

  /**
   * Returns the value of the '<em><b>Ffmpeg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ffmpeg</em>' attribute.
   * @see #setFfmpeg(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getGeneratorInformation_Ffmpeg()
   * @model
   * @generated
   */
  String getFfmpeg();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getFfmpeg <em>Ffmpeg</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ffmpeg</em>' attribute.
   * @see #getFfmpeg()
   * @generated
   */
  void setFfmpeg(String value);

  /**
   * Returns the value of the '<em><b>Ffprobe</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ffprobe</em>' attribute.
   * @see #setFfprobe(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getGeneratorInformation_Ffprobe()
   * @model
   * @generated
   */
  String getFfprobe();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getFfprobe <em>Ffprobe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ffprobe</em>' attribute.
   * @see #getFfprobe()
   * @generated
   */
  void setFfprobe(String value);

  /**
   * Returns the value of the '<em><b>Library</b></em>' containment reference list.
   * The list contents are of type {@link fr.ytpdsl.ytpDsl.VideoLibrary}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Library</em>' containment reference list.
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getGeneratorInformation_Library()
   * @model containment="true"
   * @generated
   */
  EList<VideoLibrary> getLibrary();

} // GeneratorInformation
