/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Media</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ytpdsl.ytpDsl.Media#getDescription <em>Description</em>}</li>
 * </ul>
 *
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getMedia()
 * @model
 * @generated
 */
public interface Media extends EObject
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' containment reference.
   * @see #setDescription(MediaDescription)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getMedia_Description()
   * @model containment="true"
   * @generated
   */
  MediaDescription getDescription();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.Media#getDescription <em>Description</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' containment reference.
   * @see #getDescription()
   * @generated
   */
  void setDescription(MediaDescription value);

} // Media
