/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Media Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ytpdsl.ytpDsl.MediaDescription#getLocation <em>Location</em>}</li>
 * </ul>
 *
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getMediaDescription()
 * @model
 * @generated
 */
public interface MediaDescription extends EObject
{
  /**
   * Returns the value of the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Location</em>' attribute.
   * @see #setLocation(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getMediaDescription_Location()
   * @model
   * @generated
   */
  String getLocation();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.MediaDescription#getLocation <em>Location</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Location</em>' attribute.
   * @see #getLocation()
   * @generated
   */
  void setLocation(String value);

} // MediaDescription
