/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negate Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getNegateFilter()
 * @model
 * @generated
 */
public interface NegateFilter extends Filter
{
} // NegateFilter
