/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Video Description</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ytpdsl.ytpDsl.VideoDescription#getVideoid <em>Videoid</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.VideoDescription#getDuration <em>Duration</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.VideoDescription#getProbability <em>Probability</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.VideoDescription#getDescription <em>Description</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.VideoDescription#getFilter <em>Filter</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.VideoDescription#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoDescription()
 * @model
 * @generated
 */
public interface VideoDescription extends MediaDescription
{
  /**
   * Returns the value of the '<em><b>Videoid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Videoid</em>' attribute.
   * @see #setVideoid(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoDescription_Videoid()
   * @model
   * @generated
   */
  String getVideoid();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.VideoDescription#getVideoid <em>Videoid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Videoid</em>' attribute.
   * @see #getVideoid()
   * @generated
   */
  void setVideoid(String value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' attribute.
   * @see #setDuration(int)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoDescription_Duration()
   * @model
   * @generated
   */
  int getDuration();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.VideoDescription#getDuration <em>Duration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' attribute.
   * @see #getDuration()
   * @generated
   */
  void setDuration(int value);

  /**
   * Returns the value of the '<em><b>Probability</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Probability</em>' attribute.
   * @see #setProbability(int)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoDescription_Probability()
   * @model
   * @generated
   */
  int getProbability();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.VideoDescription#getProbability <em>Probability</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Probability</em>' attribute.
   * @see #getProbability()
   * @generated
   */
  void setProbability(int value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoDescription_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.VideoDescription#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filter</em>' containment reference.
   * @see #setFilter(Filter)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoDescription_Filter()
   * @model containment="true"
   * @generated
   */
  Filter getFilter();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.VideoDescription#getFilter <em>Filter</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filter</em>' containment reference.
   * @see #getFilter()
   * @generated
   */
  void setFilter(Filter value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(VideoText)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoDescription_Text()
   * @model containment="true"
   * @generated
   */
  VideoText getText();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.VideoDescription#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(VideoText value);

} // VideoDescription
