/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Video Library</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ytpdsl.ytpDsl.VideoLibrary#getFolder <em>Folder</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.VideoLibrary#getExtension <em>Extension</em>}</li>
 * </ul>
 *
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoLibrary()
 * @model
 * @generated
 */
public interface VideoLibrary extends EObject
{
  /**
   * Returns the value of the '<em><b>Folder</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Folder</em>' attribute.
   * @see #setFolder(String)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoLibrary_Folder()
   * @model
   * @generated
   */
  String getFolder();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.VideoLibrary#getFolder <em>Folder</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Folder</em>' attribute.
   * @see #getFolder()
   * @generated
   */
  void setFolder(String value);

  /**
   * Returns the value of the '<em><b>Extension</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extension</em>' attribute list.
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getVideoLibrary_Extension()
   * @model unique="false"
   * @generated
   */
  EList<String> getExtension();

} // VideoLibrary
