/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage
 * @generated
 */
public interface YtpDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  YtpDslFactory eINSTANCE = fr.ytpdsl.ytpDsl.impl.YtpDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Ytp Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ytp Model</em>'.
   * @generated
   */
  YtpModel createYtpModel();

  /**
   * Returns a new object of class '<em>Generator Information</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Generator Information</em>'.
   * @generated
   */
  GeneratorInformation createGeneratorInformation();

  /**
   * Returns a new object of class '<em>Video Library</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Video Library</em>'.
   * @generated
   */
  VideoLibrary createVideoLibrary();

  /**
   * Returns a new object of class '<em>Media</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Media</em>'.
   * @generated
   */
  Media createMedia();

  /**
   * Returns a new object of class '<em>Media Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Media Description</em>'.
   * @generated
   */
  MediaDescription createMediaDescription();

  /**
   * Returns a new object of class '<em>Image Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Image Description</em>'.
   * @generated
   */
  ImageDescription createImageDescription();

  /**
   * Returns a new object of class '<em>Video Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Video Description</em>'.
   * @generated
   */
  VideoDescription createVideoDescription();

  /**
   * Returns a new object of class '<em>Video Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Video Text</em>'.
   * @generated
   */
  VideoText createVideoText();

  /**
   * Returns a new object of class '<em>Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter</em>'.
   * @generated
   */
  Filter createFilter();

  /**
   * Returns a new object of class '<em>Black White Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Black White Filter</em>'.
   * @generated
   */
  BlackWhiteFilter createBlackWhiteFilter();

  /**
   * Returns a new object of class '<em>Negate Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Negate Filter</em>'.
   * @generated
   */
  NegateFilter createNegateFilter();

  /**
   * Returns a new object of class '<em>Flip Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flip Filter</em>'.
   * @generated
   */
  FlipFilter createFlipFilter();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  YtpDslPackage getYtpDslPackage();

} //YtpDslFactory
