/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see fr.ytpdsl.ytpDsl.YtpDslFactory
 * @model kind="package"
 * @generated
 */
public interface YtpDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ytpDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ytpdsl.fr/YtpDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ytpDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  YtpDslPackage eINSTANCE = fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl.init();

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.YtpModelImpl <em>Ytp Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.YtpModelImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getYtpModel()
   * @generated
   */
  int YTP_MODEL = 0;

  /**
   * The feature id for the '<em><b>Information</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YTP_MODEL__INFORMATION = 0;

  /**
   * The feature id for the '<em><b>Medias</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YTP_MODEL__MEDIAS = 1;

  /**
   * The number of structural features of the '<em>Ytp Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int YTP_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.GeneratorInformationImpl <em>Generator Information</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.GeneratorInformationImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getGeneratorInformation()
   * @generated
   */
  int GENERATOR_INFORMATION = 1;

  /**
   * The feature id for the '<em><b>Author Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERATOR_INFORMATION__AUTHOR_NAME = 0;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERATOR_INFORMATION__VERSION = 1;

  /**
   * The feature id for the '<em><b>Creation Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERATOR_INFORMATION__CREATION_DATE = 2;

  /**
   * The feature id for the '<em><b>Ffmpeg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERATOR_INFORMATION__FFMPEG = 3;

  /**
   * The feature id for the '<em><b>Ffprobe</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERATOR_INFORMATION__FFPROBE = 4;

  /**
   * The feature id for the '<em><b>Library</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERATOR_INFORMATION__LIBRARY = 5;

  /**
   * The number of structural features of the '<em>Generator Information</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GENERATOR_INFORMATION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.VideoLibraryImpl <em>Video Library</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.VideoLibraryImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getVideoLibrary()
   * @generated
   */
  int VIDEO_LIBRARY = 2;

  /**
   * The feature id for the '<em><b>Folder</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_LIBRARY__FOLDER = 0;

  /**
   * The feature id for the '<em><b>Extension</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_LIBRARY__EXTENSION = 1;

  /**
   * The number of structural features of the '<em>Video Library</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_LIBRARY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.MediaImpl <em>Media</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.MediaImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getMedia()
   * @generated
   */
  int MEDIA = 3;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIA__DESCRIPTION = 0;

  /**
   * The number of structural features of the '<em>Media</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.MediaDescriptionImpl <em>Media Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.MediaDescriptionImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getMediaDescription()
   * @generated
   */
  int MEDIA_DESCRIPTION = 4;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIA_DESCRIPTION__LOCATION = 0;

  /**
   * The number of structural features of the '<em>Media Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIA_DESCRIPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.ImageDescriptionImpl <em>Image Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.ImageDescriptionImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getImageDescription()
   * @generated
   */
  int IMAGE_DESCRIPTION = 5;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION__LOCATION = MEDIA_DESCRIPTION__LOCATION;

  /**
   * The feature id for the '<em><b>Imageid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION__IMAGEID = MEDIA_DESCRIPTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Top</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION__TOP = MEDIA_DESCRIPTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Bottom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION__BOTTOM = MEDIA_DESCRIPTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Image Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION_FEATURE_COUNT = MEDIA_DESCRIPTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.VideoDescriptionImpl <em>Video Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.VideoDescriptionImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getVideoDescription()
   * @generated
   */
  int VIDEO_DESCRIPTION = 6;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__LOCATION = MEDIA_DESCRIPTION__LOCATION;

  /**
   * The feature id for the '<em><b>Videoid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__VIDEOID = MEDIA_DESCRIPTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__DURATION = MEDIA_DESCRIPTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Probability</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__PROBABILITY = MEDIA_DESCRIPTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__DESCRIPTION = MEDIA_DESCRIPTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__FILTER = MEDIA_DESCRIPTION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__TEXT = MEDIA_DESCRIPTION_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Video Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION_FEATURE_COUNT = MEDIA_DESCRIPTION_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.VideoTextImpl <em>Video Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.VideoTextImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getVideoText()
   * @generated
   */
  int VIDEO_TEXT = 7;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT__CONTENT = 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT__POSITION = 1;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT__COLOR = 2;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT__SIZE = 3;

  /**
   * The number of structural features of the '<em>Video Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.FilterImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 8;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.BlackWhiteFilterImpl <em>Black White Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.BlackWhiteFilterImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getBlackWhiteFilter()
   * @generated
   */
  int BLACK_WHITE_FILTER = 9;

  /**
   * The number of structural features of the '<em>Black White Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLACK_WHITE_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.NegateFilterImpl <em>Negate Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.NegateFilterImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getNegateFilter()
   * @generated
   */
  int NEGATE_FILTER = 10;

  /**
   * The number of structural features of the '<em>Negate Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATE_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link fr.ytpdsl.ytpDsl.impl.FlipFilterImpl <em>Flip Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see fr.ytpdsl.ytpDsl.impl.FlipFilterImpl
   * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getFlipFilter()
   * @generated
   */
  int FLIP_FILTER = 11;

  /**
   * The feature id for the '<em><b>Orientation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIP_FILTER__ORIENTATION = FILTER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Flip Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIP_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.YtpModel <em>Ytp Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ytp Model</em>'.
   * @see fr.ytpdsl.ytpDsl.YtpModel
   * @generated
   */
  EClass getYtpModel();

  /**
   * Returns the meta object for the containment reference '{@link fr.ytpdsl.ytpDsl.YtpModel#getInformation <em>Information</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Information</em>'.
   * @see fr.ytpdsl.ytpDsl.YtpModel#getInformation()
   * @see #getYtpModel()
   * @generated
   */
  EReference getYtpModel_Information();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ytpdsl.ytpDsl.YtpModel#getMedias <em>Medias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Medias</em>'.
   * @see fr.ytpdsl.ytpDsl.YtpModel#getMedias()
   * @see #getYtpModel()
   * @generated
   */
  EReference getYtpModel_Medias();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.GeneratorInformation <em>Generator Information</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Generator Information</em>'.
   * @see fr.ytpdsl.ytpDsl.GeneratorInformation
   * @generated
   */
  EClass getGeneratorInformation();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getAuthorName <em>Author Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Author Name</em>'.
   * @see fr.ytpdsl.ytpDsl.GeneratorInformation#getAuthorName()
   * @see #getGeneratorInformation()
   * @generated
   */
  EAttribute getGeneratorInformation_AuthorName();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see fr.ytpdsl.ytpDsl.GeneratorInformation#getVersion()
   * @see #getGeneratorInformation()
   * @generated
   */
  EAttribute getGeneratorInformation_Version();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getCreationDate <em>Creation Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Creation Date</em>'.
   * @see fr.ytpdsl.ytpDsl.GeneratorInformation#getCreationDate()
   * @see #getGeneratorInformation()
   * @generated
   */
  EAttribute getGeneratorInformation_CreationDate();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getFfmpeg <em>Ffmpeg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ffmpeg</em>'.
   * @see fr.ytpdsl.ytpDsl.GeneratorInformation#getFfmpeg()
   * @see #getGeneratorInformation()
   * @generated
   */
  EAttribute getGeneratorInformation_Ffmpeg();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getFfprobe <em>Ffprobe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ffprobe</em>'.
   * @see fr.ytpdsl.ytpDsl.GeneratorInformation#getFfprobe()
   * @see #getGeneratorInformation()
   * @generated
   */
  EAttribute getGeneratorInformation_Ffprobe();

  /**
   * Returns the meta object for the containment reference list '{@link fr.ytpdsl.ytpDsl.GeneratorInformation#getLibrary <em>Library</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Library</em>'.
   * @see fr.ytpdsl.ytpDsl.GeneratorInformation#getLibrary()
   * @see #getGeneratorInformation()
   * @generated
   */
  EReference getGeneratorInformation_Library();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.VideoLibrary <em>Video Library</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Library</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoLibrary
   * @generated
   */
  EClass getVideoLibrary();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.VideoLibrary#getFolder <em>Folder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Folder</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoLibrary#getFolder()
   * @see #getVideoLibrary()
   * @generated
   */
  EAttribute getVideoLibrary_Folder();

  /**
   * Returns the meta object for the attribute list '{@link fr.ytpdsl.ytpDsl.VideoLibrary#getExtension <em>Extension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Extension</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoLibrary#getExtension()
   * @see #getVideoLibrary()
   * @generated
   */
  EAttribute getVideoLibrary_Extension();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.Media <em>Media</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Media</em>'.
   * @see fr.ytpdsl.ytpDsl.Media
   * @generated
   */
  EClass getMedia();

  /**
   * Returns the meta object for the containment reference '{@link fr.ytpdsl.ytpDsl.Media#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see fr.ytpdsl.ytpDsl.Media#getDescription()
   * @see #getMedia()
   * @generated
   */
  EReference getMedia_Description();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.MediaDescription <em>Media Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Media Description</em>'.
   * @see fr.ytpdsl.ytpDsl.MediaDescription
   * @generated
   */
  EClass getMediaDescription();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.MediaDescription#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see fr.ytpdsl.ytpDsl.MediaDescription#getLocation()
   * @see #getMediaDescription()
   * @generated
   */
  EAttribute getMediaDescription_Location();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.ImageDescription <em>Image Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image Description</em>'.
   * @see fr.ytpdsl.ytpDsl.ImageDescription
   * @generated
   */
  EClass getImageDescription();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.ImageDescription#getImageid <em>Imageid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imageid</em>'.
   * @see fr.ytpdsl.ytpDsl.ImageDescription#getImageid()
   * @see #getImageDescription()
   * @generated
   */
  EAttribute getImageDescription_Imageid();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.ImageDescription#getTop <em>Top</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Top</em>'.
   * @see fr.ytpdsl.ytpDsl.ImageDescription#getTop()
   * @see #getImageDescription()
   * @generated
   */
  EAttribute getImageDescription_Top();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.ImageDescription#getBottom <em>Bottom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bottom</em>'.
   * @see fr.ytpdsl.ytpDsl.ImageDescription#getBottom()
   * @see #getImageDescription()
   * @generated
   */
  EAttribute getImageDescription_Bottom();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.VideoDescription <em>Video Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Description</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoDescription
   * @generated
   */
  EClass getVideoDescription();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.VideoDescription#getVideoid <em>Videoid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Videoid</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoDescription#getVideoid()
   * @see #getVideoDescription()
   * @generated
   */
  EAttribute getVideoDescription_Videoid();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.VideoDescription#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoDescription#getDuration()
   * @see #getVideoDescription()
   * @generated
   */
  EAttribute getVideoDescription_Duration();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.VideoDescription#getProbability <em>Probability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Probability</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoDescription#getProbability()
   * @see #getVideoDescription()
   * @generated
   */
  EAttribute getVideoDescription_Probability();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.VideoDescription#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoDescription#getDescription()
   * @see #getVideoDescription()
   * @generated
   */
  EAttribute getVideoDescription_Description();

  /**
   * Returns the meta object for the containment reference '{@link fr.ytpdsl.ytpDsl.VideoDescription#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoDescription#getFilter()
   * @see #getVideoDescription()
   * @generated
   */
  EReference getVideoDescription_Filter();

  /**
   * Returns the meta object for the containment reference '{@link fr.ytpdsl.ytpDsl.VideoDescription#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoDescription#getText()
   * @see #getVideoDescription()
   * @generated
   */
  EReference getVideoDescription_Text();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.VideoText <em>Video Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Text</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoText
   * @generated
   */
  EClass getVideoText();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.VideoText#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoText#getContent()
   * @see #getVideoText()
   * @generated
   */
  EAttribute getVideoText_Content();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.VideoText#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Position</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoText#getPosition()
   * @see #getVideoText()
   * @generated
   */
  EAttribute getVideoText_Position();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.VideoText#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoText#getColor()
   * @see #getVideoText()
   * @generated
   */
  EAttribute getVideoText_Color();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.VideoText#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see fr.ytpdsl.ytpDsl.VideoText#getSize()
   * @see #getVideoText()
   * @generated
   */
  EAttribute getVideoText_Size();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see fr.ytpdsl.ytpDsl.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.BlackWhiteFilter <em>Black White Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Black White Filter</em>'.
   * @see fr.ytpdsl.ytpDsl.BlackWhiteFilter
   * @generated
   */
  EClass getBlackWhiteFilter();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.NegateFilter <em>Negate Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Negate Filter</em>'.
   * @see fr.ytpdsl.ytpDsl.NegateFilter
   * @generated
   */
  EClass getNegateFilter();

  /**
   * Returns the meta object for class '{@link fr.ytpdsl.ytpDsl.FlipFilter <em>Flip Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flip Filter</em>'.
   * @see fr.ytpdsl.ytpDsl.FlipFilter
   * @generated
   */
  EClass getFlipFilter();

  /**
   * Returns the meta object for the attribute '{@link fr.ytpdsl.ytpDsl.FlipFilter#getOrientation <em>Orientation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Orientation</em>'.
   * @see fr.ytpdsl.ytpDsl.FlipFilter#getOrientation()
   * @see #getFlipFilter()
   * @generated
   */
  EAttribute getFlipFilter_Orientation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  YtpDslFactory getYtpDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.YtpModelImpl <em>Ytp Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.YtpModelImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getYtpModel()
     * @generated
     */
    EClass YTP_MODEL = eINSTANCE.getYtpModel();

    /**
     * The meta object literal for the '<em><b>Information</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YTP_MODEL__INFORMATION = eINSTANCE.getYtpModel_Information();

    /**
     * The meta object literal for the '<em><b>Medias</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference YTP_MODEL__MEDIAS = eINSTANCE.getYtpModel_Medias();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.GeneratorInformationImpl <em>Generator Information</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.GeneratorInformationImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getGeneratorInformation()
     * @generated
     */
    EClass GENERATOR_INFORMATION = eINSTANCE.getGeneratorInformation();

    /**
     * The meta object literal for the '<em><b>Author Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERATOR_INFORMATION__AUTHOR_NAME = eINSTANCE.getGeneratorInformation_AuthorName();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERATOR_INFORMATION__VERSION = eINSTANCE.getGeneratorInformation_Version();

    /**
     * The meta object literal for the '<em><b>Creation Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERATOR_INFORMATION__CREATION_DATE = eINSTANCE.getGeneratorInformation_CreationDate();

    /**
     * The meta object literal for the '<em><b>Ffmpeg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERATOR_INFORMATION__FFMPEG = eINSTANCE.getGeneratorInformation_Ffmpeg();

    /**
     * The meta object literal for the '<em><b>Ffprobe</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GENERATOR_INFORMATION__FFPROBE = eINSTANCE.getGeneratorInformation_Ffprobe();

    /**
     * The meta object literal for the '<em><b>Library</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GENERATOR_INFORMATION__LIBRARY = eINSTANCE.getGeneratorInformation_Library();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.VideoLibraryImpl <em>Video Library</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.VideoLibraryImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getVideoLibrary()
     * @generated
     */
    EClass VIDEO_LIBRARY = eINSTANCE.getVideoLibrary();

    /**
     * The meta object literal for the '<em><b>Folder</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_LIBRARY__FOLDER = eINSTANCE.getVideoLibrary_Folder();

    /**
     * The meta object literal for the '<em><b>Extension</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_LIBRARY__EXTENSION = eINSTANCE.getVideoLibrary_Extension();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.MediaImpl <em>Media</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.MediaImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getMedia()
     * @generated
     */
    EClass MEDIA = eINSTANCE.getMedia();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MEDIA__DESCRIPTION = eINSTANCE.getMedia_Description();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.MediaDescriptionImpl <em>Media Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.MediaDescriptionImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getMediaDescription()
     * @generated
     */
    EClass MEDIA_DESCRIPTION = eINSTANCE.getMediaDescription();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDIA_DESCRIPTION__LOCATION = eINSTANCE.getMediaDescription_Location();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.ImageDescriptionImpl <em>Image Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.ImageDescriptionImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getImageDescription()
     * @generated
     */
    EClass IMAGE_DESCRIPTION = eINSTANCE.getImageDescription();

    /**
     * The meta object literal for the '<em><b>Imageid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE_DESCRIPTION__IMAGEID = eINSTANCE.getImageDescription_Imageid();

    /**
     * The meta object literal for the '<em><b>Top</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE_DESCRIPTION__TOP = eINSTANCE.getImageDescription_Top();

    /**
     * The meta object literal for the '<em><b>Bottom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE_DESCRIPTION__BOTTOM = eINSTANCE.getImageDescription_Bottom();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.VideoDescriptionImpl <em>Video Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.VideoDescriptionImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getVideoDescription()
     * @generated
     */
    EClass VIDEO_DESCRIPTION = eINSTANCE.getVideoDescription();

    /**
     * The meta object literal for the '<em><b>Videoid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_DESCRIPTION__VIDEOID = eINSTANCE.getVideoDescription_Videoid();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_DESCRIPTION__DURATION = eINSTANCE.getVideoDescription_Duration();

    /**
     * The meta object literal for the '<em><b>Probability</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_DESCRIPTION__PROBABILITY = eINSTANCE.getVideoDescription_Probability();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_DESCRIPTION__DESCRIPTION = eINSTANCE.getVideoDescription_Description();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_DESCRIPTION__FILTER = eINSTANCE.getVideoDescription_Filter();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_DESCRIPTION__TEXT = eINSTANCE.getVideoDescription_Text();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.VideoTextImpl <em>Video Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.VideoTextImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getVideoText()
     * @generated
     */
    EClass VIDEO_TEXT = eINSTANCE.getVideoText();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_TEXT__CONTENT = eINSTANCE.getVideoText_Content();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_TEXT__POSITION = eINSTANCE.getVideoText_Position();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_TEXT__COLOR = eINSTANCE.getVideoText_Color();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_TEXT__SIZE = eINSTANCE.getVideoText_Size();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.FilterImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.BlackWhiteFilterImpl <em>Black White Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.BlackWhiteFilterImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getBlackWhiteFilter()
     * @generated
     */
    EClass BLACK_WHITE_FILTER = eINSTANCE.getBlackWhiteFilter();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.NegateFilterImpl <em>Negate Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.NegateFilterImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getNegateFilter()
     * @generated
     */
    EClass NEGATE_FILTER = eINSTANCE.getNegateFilter();

    /**
     * The meta object literal for the '{@link fr.ytpdsl.ytpDsl.impl.FlipFilterImpl <em>Flip Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see fr.ytpdsl.ytpDsl.impl.FlipFilterImpl
     * @see fr.ytpdsl.ytpDsl.impl.YtpDslPackageImpl#getFlipFilter()
     * @generated
     */
    EClass FLIP_FILTER = eINSTANCE.getFlipFilter();

    /**
     * The meta object literal for the '<em><b>Orientation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLIP_FILTER__ORIENTATION = eINSTANCE.getFlipFilter_Orientation();

  }

} //YtpDslPackage
