/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ytp Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.ytpdsl.ytpDsl.YtpModel#getInformation <em>Information</em>}</li>
 *   <li>{@link fr.ytpdsl.ytpDsl.YtpModel#getMedias <em>Medias</em>}</li>
 * </ul>
 *
 * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getYtpModel()
 * @model
 * @generated
 */
public interface YtpModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Information</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Information</em>' containment reference.
   * @see #setInformation(GeneratorInformation)
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getYtpModel_Information()
   * @model containment="true"
   * @generated
   */
  GeneratorInformation getInformation();

  /**
   * Sets the value of the '{@link fr.ytpdsl.ytpDsl.YtpModel#getInformation <em>Information</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Information</em>' containment reference.
   * @see #getInformation()
   * @generated
   */
  void setInformation(GeneratorInformation value);

  /**
   * Returns the value of the '<em><b>Medias</b></em>' containment reference list.
   * The list contents are of type {@link fr.ytpdsl.ytpDsl.Media}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Medias</em>' containment reference list.
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#getYtpModel_Medias()
   * @model containment="true"
   * @generated
   */
  EList<Media> getMedias();

} // YtpModel
