/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ide;

import fr.ytpdsl.ide.AbstractYtpDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class YtpDslIdeModule extends AbstractYtpDslIdeModule {
}
