/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.ytpdsl.YtpDslRuntimeModule;
import fr.ytpdsl.YtpDslStandaloneSetup;
import fr.ytpdsl.ide.YtpDslIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class YtpDslIdeSetup extends YtpDslStandaloneSetup {
  @Override
  public Injector createInjector() {
    YtpDslRuntimeModule _ytpDslRuntimeModule = new YtpDslRuntimeModule();
    YtpDslIdeModule _ytpDslIdeModule = new YtpDslIdeModule();
    return Guice.createInjector(Modules2.mixin(_ytpDslRuntimeModule, _ytpDslIdeModule));
  }
}
