/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl;

import fr.ytpdsl.YtpDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class YtpDslStandaloneSetup extends YtpDslStandaloneSetupGenerated {
  public static void doSetup() {
    new YtpDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
