/*
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class YtpDslUiModule extends AbstractYtpDslUiModule {
}
