/*
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ui.tests;

import com.google.inject.Injector;
import fr.ytpdsl.ui.internal.YtpdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class YtpDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return YtpdslActivator.getInstance().getInjector("fr.ytpdsl.YtpDsl");
	}

}
