/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.validation;

import fr.ytpdsl.validation.AbstractYtpDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class YtpDslValidator extends AbstractYtpDslValidator {
}
