/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ui.contentassist;

import fr.ytpdsl.ui.contentassist.AbstractYtpDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class YtpDslProposalProvider extends AbstractYtpDslProposalProvider {
}
