/*
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class YtpDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/ytpdsl/parser/antlr/internal/InternalYtpDsl.tokens");
	}
}
