/*
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.parser.antlr;

import com.google.inject.Inject;
import fr.ytpdsl.parser.antlr.internal.InternalYtpDslParser;
import fr.ytpdsl.services.YtpDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class YtpDslParser extends AbstractAntlrParser {

	@Inject
	private YtpDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalYtpDslParser createParser(XtextTokenStream stream) {
		return new InternalYtpDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "YtpModel";
	}

	public YtpDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(YtpDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
