/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ui;

import fr.ytpdsl.ui.AbstractYtpDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class YtpDslUiModule extends AbstractYtpDslUiModule {
  public YtpDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
