/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl.impl;

import fr.ytpdsl.ytpDsl.BlackWhiteFilter;
import fr.ytpdsl.ytpDsl.YtpDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Black White Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BlackWhiteFilterImpl extends FilterImpl implements BlackWhiteFilter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BlackWhiteFilterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return YtpDslPackage.Literals.BLACK_WHITE_FILTER;
  }

} //BlackWhiteFilterImpl
