/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl.impl;

import fr.ytpdsl.ytpDsl.Filter;
import fr.ytpdsl.ytpDsl.YtpDslPackage;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FilterImpl extends MinimalEObjectImpl.Container implements Filter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FilterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return YtpDslPackage.Literals.FILTER;
  }

} //FilterImpl
