/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl.impl;

import fr.ytpdsl.ytpDsl.NegateFilter;
import fr.ytpdsl.ytpDsl.YtpDslPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Negate Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NegateFilterImpl extends FilterImpl implements NegateFilter
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NegateFilterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return YtpDslPackage.Literals.NEGATE_FILTER;
  }

} //NegateFilterImpl
