/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl.impl;

import fr.ytpdsl.ytpDsl.BlackWhiteFilter;
import fr.ytpdsl.ytpDsl.Filter;
import fr.ytpdsl.ytpDsl.FlipFilter;
import fr.ytpdsl.ytpDsl.GeneratorInformation;
import fr.ytpdsl.ytpDsl.ImageDescription;
import fr.ytpdsl.ytpDsl.Media;
import fr.ytpdsl.ytpDsl.MediaDescription;
import fr.ytpdsl.ytpDsl.NegateFilter;
import fr.ytpdsl.ytpDsl.VideoDescription;
import fr.ytpdsl.ytpDsl.VideoLibrary;
import fr.ytpdsl.ytpDsl.VideoText;
import fr.ytpdsl.ytpDsl.YtpDslFactory;
import fr.ytpdsl.ytpDsl.YtpDslPackage;
import fr.ytpdsl.ytpDsl.YtpModel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class YtpDslPackageImpl extends EPackageImpl implements YtpDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass ytpModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass generatorInformationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass videoLibraryEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mediaEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass mediaDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass imageDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass videoDescriptionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass videoTextEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass filterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass blackWhiteFilterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass negateFilterEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass flipFilterEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see fr.ytpdsl.ytpDsl.YtpDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private YtpDslPackageImpl()
  {
    super(eNS_URI, YtpDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link YtpDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static YtpDslPackage init()
  {
    if (isInited) return (YtpDslPackage)EPackage.Registry.INSTANCE.getEPackage(YtpDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredYtpDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    YtpDslPackageImpl theYtpDslPackage = registeredYtpDslPackage instanceof YtpDslPackageImpl ? (YtpDslPackageImpl)registeredYtpDslPackage : new YtpDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theYtpDslPackage.createPackageContents();

    // Initialize created meta-data
    theYtpDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theYtpDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(YtpDslPackage.eNS_URI, theYtpDslPackage);
    return theYtpDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getYtpModel()
  {
    return ytpModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getYtpModel_Information()
  {
    return (EReference)ytpModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getYtpModel_Medias()
  {
    return (EReference)ytpModelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getGeneratorInformation()
  {
    return generatorInformationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneratorInformation_AuthorName()
  {
    return (EAttribute)generatorInformationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneratorInformation_Version()
  {
    return (EAttribute)generatorInformationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneratorInformation_CreationDate()
  {
    return (EAttribute)generatorInformationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneratorInformation_Ffmpeg()
  {
    return (EAttribute)generatorInformationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getGeneratorInformation_Ffprobe()
  {
    return (EAttribute)generatorInformationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getGeneratorInformation_Library()
  {
    return (EReference)generatorInformationEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVideoLibrary()
  {
    return videoLibraryEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoLibrary_Folder()
  {
    return (EAttribute)videoLibraryEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoLibrary_Extension()
  {
    return (EAttribute)videoLibraryEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMedia()
  {
    return mediaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMedia_Description()
  {
    return (EReference)mediaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMediaDescription()
  {
    return mediaDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMediaDescription_Location()
  {
    return (EAttribute)mediaDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getImageDescription()
  {
    return imageDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImageDescription_Imageid()
  {
    return (EAttribute)imageDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImageDescription_Top()
  {
    return (EAttribute)imageDescriptionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getImageDescription_Bottom()
  {
    return (EAttribute)imageDescriptionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVideoDescription()
  {
    return videoDescriptionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoDescription_Videoid()
  {
    return (EAttribute)videoDescriptionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoDescription_Duration()
  {
    return (EAttribute)videoDescriptionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoDescription_Probability()
  {
    return (EAttribute)videoDescriptionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoDescription_Description()
  {
    return (EAttribute)videoDescriptionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVideoDescription_Filter()
  {
    return (EReference)videoDescriptionEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getVideoDescription_Text()
  {
    return (EReference)videoDescriptionEClass.getEStructuralFeatures().get(5);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVideoText()
  {
    return videoTextEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoText_Content()
  {
    return (EAttribute)videoTextEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoText_Position()
  {
    return (EAttribute)videoTextEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoText_Color()
  {
    return (EAttribute)videoTextEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVideoText_Size()
  {
    return (EAttribute)videoTextEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFilter()
  {
    return filterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getBlackWhiteFilter()
  {
    return blackWhiteFilterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNegateFilter()
  {
    return negateFilterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFlipFilter()
  {
    return flipFilterEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFlipFilter_Orientation()
  {
    return (EAttribute)flipFilterEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public YtpDslFactory getYtpDslFactory()
  {
    return (YtpDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    ytpModelEClass = createEClass(YTP_MODEL);
    createEReference(ytpModelEClass, YTP_MODEL__INFORMATION);
    createEReference(ytpModelEClass, YTP_MODEL__MEDIAS);

    generatorInformationEClass = createEClass(GENERATOR_INFORMATION);
    createEAttribute(generatorInformationEClass, GENERATOR_INFORMATION__AUTHOR_NAME);
    createEAttribute(generatorInformationEClass, GENERATOR_INFORMATION__VERSION);
    createEAttribute(generatorInformationEClass, GENERATOR_INFORMATION__CREATION_DATE);
    createEAttribute(generatorInformationEClass, GENERATOR_INFORMATION__FFMPEG);
    createEAttribute(generatorInformationEClass, GENERATOR_INFORMATION__FFPROBE);
    createEReference(generatorInformationEClass, GENERATOR_INFORMATION__LIBRARY);

    videoLibraryEClass = createEClass(VIDEO_LIBRARY);
    createEAttribute(videoLibraryEClass, VIDEO_LIBRARY__FOLDER);
    createEAttribute(videoLibraryEClass, VIDEO_LIBRARY__EXTENSION);

    mediaEClass = createEClass(MEDIA);
    createEReference(mediaEClass, MEDIA__DESCRIPTION);

    mediaDescriptionEClass = createEClass(MEDIA_DESCRIPTION);
    createEAttribute(mediaDescriptionEClass, MEDIA_DESCRIPTION__LOCATION);

    imageDescriptionEClass = createEClass(IMAGE_DESCRIPTION);
    createEAttribute(imageDescriptionEClass, IMAGE_DESCRIPTION__IMAGEID);
    createEAttribute(imageDescriptionEClass, IMAGE_DESCRIPTION__TOP);
    createEAttribute(imageDescriptionEClass, IMAGE_DESCRIPTION__BOTTOM);

    videoDescriptionEClass = createEClass(VIDEO_DESCRIPTION);
    createEAttribute(videoDescriptionEClass, VIDEO_DESCRIPTION__VIDEOID);
    createEAttribute(videoDescriptionEClass, VIDEO_DESCRIPTION__DURATION);
    createEAttribute(videoDescriptionEClass, VIDEO_DESCRIPTION__PROBABILITY);
    createEAttribute(videoDescriptionEClass, VIDEO_DESCRIPTION__DESCRIPTION);
    createEReference(videoDescriptionEClass, VIDEO_DESCRIPTION__FILTER);
    createEReference(videoDescriptionEClass, VIDEO_DESCRIPTION__TEXT);

    videoTextEClass = createEClass(VIDEO_TEXT);
    createEAttribute(videoTextEClass, VIDEO_TEXT__CONTENT);
    createEAttribute(videoTextEClass, VIDEO_TEXT__POSITION);
    createEAttribute(videoTextEClass, VIDEO_TEXT__COLOR);
    createEAttribute(videoTextEClass, VIDEO_TEXT__SIZE);

    filterEClass = createEClass(FILTER);

    blackWhiteFilterEClass = createEClass(BLACK_WHITE_FILTER);

    negateFilterEClass = createEClass(NEGATE_FILTER);

    flipFilterEClass = createEClass(FLIP_FILTER);
    createEAttribute(flipFilterEClass, FLIP_FILTER__ORIENTATION);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    imageDescriptionEClass.getESuperTypes().add(this.getMediaDescription());
    videoDescriptionEClass.getESuperTypes().add(this.getMediaDescription());
    blackWhiteFilterEClass.getESuperTypes().add(this.getFilter());
    negateFilterEClass.getESuperTypes().add(this.getFilter());
    flipFilterEClass.getESuperTypes().add(this.getFilter());

    // Initialize classes and features; add operations and parameters
    initEClass(ytpModelEClass, YtpModel.class, "YtpModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getYtpModel_Information(), this.getGeneratorInformation(), null, "information", null, 0, 1, YtpModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getYtpModel_Medias(), this.getMedia(), null, "medias", null, 0, -1, YtpModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(generatorInformationEClass, GeneratorInformation.class, "GeneratorInformation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getGeneratorInformation_AuthorName(), ecorePackage.getEString(), "authorName", null, 0, 1, GeneratorInformation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGeneratorInformation_Version(), ecorePackage.getEString(), "version", null, 0, 1, GeneratorInformation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGeneratorInformation_CreationDate(), ecorePackage.getEString(), "creationDate", null, 0, 1, GeneratorInformation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGeneratorInformation_Ffmpeg(), ecorePackage.getEString(), "ffmpeg", null, 0, 1, GeneratorInformation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getGeneratorInformation_Ffprobe(), ecorePackage.getEString(), "ffprobe", null, 0, 1, GeneratorInformation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getGeneratorInformation_Library(), this.getVideoLibrary(), null, "library", null, 0, -1, GeneratorInformation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(videoLibraryEClass, VideoLibrary.class, "VideoLibrary", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVideoLibrary_Folder(), ecorePackage.getEString(), "folder", null, 0, 1, VideoLibrary.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVideoLibrary_Extension(), ecorePackage.getEString(), "extension", null, 0, -1, VideoLibrary.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mediaEClass, Media.class, "Media", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMedia_Description(), this.getMediaDescription(), null, "description", null, 0, 1, Media.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(mediaDescriptionEClass, MediaDescription.class, "MediaDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMediaDescription_Location(), ecorePackage.getEString(), "location", null, 0, 1, MediaDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(imageDescriptionEClass, ImageDescription.class, "ImageDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getImageDescription_Imageid(), ecorePackage.getEString(), "imageid", null, 0, 1, ImageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getImageDescription_Top(), ecorePackage.getEString(), "top", null, 0, 1, ImageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getImageDescription_Bottom(), ecorePackage.getEString(), "bottom", null, 0, 1, ImageDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(videoDescriptionEClass, VideoDescription.class, "VideoDescription", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVideoDescription_Videoid(), ecorePackage.getEString(), "videoid", null, 0, 1, VideoDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVideoDescription_Duration(), ecorePackage.getEInt(), "duration", null, 0, 1, VideoDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVideoDescription_Probability(), ecorePackage.getEInt(), "probability", null, 0, 1, VideoDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVideoDescription_Description(), ecorePackage.getEString(), "description", null, 0, 1, VideoDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVideoDescription_Filter(), this.getFilter(), null, "filter", null, 0, 1, VideoDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getVideoDescription_Text(), this.getVideoText(), null, "text", null, 0, 1, VideoDescription.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(videoTextEClass, VideoText.class, "VideoText", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVideoText_Content(), ecorePackage.getEString(), "content", null, 0, 1, VideoText.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVideoText_Position(), ecorePackage.getEString(), "position", null, 0, 1, VideoText.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVideoText_Color(), ecorePackage.getEString(), "color", null, 0, 1, VideoText.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVideoText_Size(), ecorePackage.getEInt(), "size", null, 0, 1, VideoText.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(filterEClass, Filter.class, "Filter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(blackWhiteFilterEClass, BlackWhiteFilter.class, "BlackWhiteFilter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(negateFilterEClass, NegateFilter.class, "NegateFilter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(flipFilterEClass, FlipFilter.class, "FlipFilter", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFlipFilter_Orientation(), ecorePackage.getEString(), "orientation", null, 0, 1, FlipFilter.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //YtpDslPackageImpl
