/**
 * generated by Xtext 2.18.0.M3
 */
package fr.ytpdsl.ytpDsl.impl;

import fr.ytpdsl.ytpDsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class YtpDslFactoryImpl extends EFactoryImpl implements YtpDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static YtpDslFactory init()
  {
    try
    {
      YtpDslFactory theYtpDslFactory = (YtpDslFactory)EPackage.Registry.INSTANCE.getEFactory(YtpDslPackage.eNS_URI);
      if (theYtpDslFactory != null)
      {
        return theYtpDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new YtpDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public YtpDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case YtpDslPackage.YTP_MODEL: return createYtpModel();
      case YtpDslPackage.GENERATOR_INFORMATION: return createGeneratorInformation();
      case YtpDslPackage.VIDEO_LIBRARY: return createVideoLibrary();
      case YtpDslPackage.MEDIA: return createMedia();
      case YtpDslPackage.MEDIA_DESCRIPTION: return createMediaDescription();
      case YtpDslPackage.IMAGE_DESCRIPTION: return createImageDescription();
      case YtpDslPackage.VIDEO_DESCRIPTION: return createVideoDescription();
      case YtpDslPackage.VIDEO_TEXT: return createVideoText();
      case YtpDslPackage.FILTER: return createFilter();
      case YtpDslPackage.BLACK_WHITE_FILTER: return createBlackWhiteFilter();
      case YtpDslPackage.NEGATE_FILTER: return createNegateFilter();
      case YtpDslPackage.FLIP_FILTER: return createFlipFilter();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public YtpModel createYtpModel()
  {
    YtpModelImpl ytpModel = new YtpModelImpl();
    return ytpModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GeneratorInformation createGeneratorInformation()
  {
    GeneratorInformationImpl generatorInformation = new GeneratorInformationImpl();
    return generatorInformation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VideoLibrary createVideoLibrary()
  {
    VideoLibraryImpl videoLibrary = new VideoLibraryImpl();
    return videoLibrary;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Media createMedia()
  {
    MediaImpl media = new MediaImpl();
    return media;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MediaDescription createMediaDescription()
  {
    MediaDescriptionImpl mediaDescription = new MediaDescriptionImpl();
    return mediaDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ImageDescription createImageDescription()
  {
    ImageDescriptionImpl imageDescription = new ImageDescriptionImpl();
    return imageDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VideoDescription createVideoDescription()
  {
    VideoDescriptionImpl videoDescription = new VideoDescriptionImpl();
    return videoDescription;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VideoText createVideoText()
  {
    VideoTextImpl videoText = new VideoTextImpl();
    return videoText;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Filter createFilter()
  {
    FilterImpl filter = new FilterImpl();
    return filter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BlackWhiteFilter createBlackWhiteFilter()
  {
    BlackWhiteFilterImpl blackWhiteFilter = new BlackWhiteFilterImpl();
    return blackWhiteFilter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NegateFilter createNegateFilter()
  {
    NegateFilterImpl negateFilter = new NegateFilterImpl();
    return negateFilter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FlipFilter createFlipFilter()
  {
    FlipFilterImpl flipFilter = new FlipFilterImpl();
    return flipFilter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public YtpDslPackage getYtpDslPackage()
  {
    return (YtpDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static YtpDslPackage getPackage()
  {
    return YtpDslPackage.eINSTANCE;
  }

} //YtpDslFactoryImpl
